config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  root to: 'welcome#index'

  resources :wikis do 
    resources :collaborators, only: [:create, :destroy]
  end
  
  resources :charges, only: [:new, :create]
  
  resources :users, only: [:update] do
    post :downgrade
    post :upgrade
  end

end

app/models/amount.rb
class Amount
  def self.default
    return 15_00
  end
end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  # Associations
  belongs_to :user
  belongs_to :wiki

  def self.wikis
    Wiki.where(id: pluck(:wiki_id))
  end

  def self.users
    User.where( id: pluck(:user_id))
  end

  def wiki
    Wiki.find(wiki_id)
  end

  def user
    User.find(user_id)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  
  # Associations
  has_many :collaborators
  has_many :wikis, through: :collaborators

  # Delegates
  delegate :wikis, to: :collaborators
  
  after_initialize :default_role

  def admin?
    role == 'admin'
  end

  def premium?
    role == 'premium'
  end

  def standard?
    role == 'standard'
  end

  private

  def default_role
    self.role ||= 'standard' # if role is false/empty then set it to 'standard'
  end

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators
  has_many :users, through: :collaborators

  scope :visible_to, -> (user) { (user.role == 'premium' || user.role == 'admin') ? all : where(private: false) }
 
  delegate :users, to: :collaborators

  def collaboration_exists?(user)
    self.users.include?(user)
  end

  def can_modify_wiki?(user)
    self.collaboration_exists?(user) || user.role == 'admin'
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?
 
  rescue_from Pundit::NotAuthorizedError do |exception|
    redirect_to root_url, alert: exception.message
  end

  protected
 
  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/charges_controller.rb
require_relative '../models/amount'

class ChargesController < ApplicationController
  def new
    @stripe_btn_data = {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "BigMoney Membership - #{current_user.name}",
      amount: Amount.default 
    }
  end

  def create
    @user = current_user

    customer = Stripe::Customer.create(
      email: @user.email,
      card: params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      customer: customer.id,
      amount: Amount.default,
      description: "Blocipedia Membership - #{@user.email}",
      currency: 'usd'
    )
    
    @user.update(role: 'premium')
    flash[:success] = "Thanks for upgrading your account, #{@user}!"
    redirect_to wikis_path

    rescue Stripe::CardError => e
      flash[:error] = e.message
      @user.update(role: 'standard') if !@was_standard # We don't want to take away their premium membership if they were premium before
      redirect_to new_charge_path
  end


end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController

  def create
    user = User.find(params[:user_id])
    wiki = Wiki.find(params[:wiki_id])
    collaborator = Collaborator.new(wiki: wiki, user: user)

    if collaborator.save
      flash[:notice] = "#{user.name} was added as a collaborator to '#{wiki.title}'"
    else
      flash[:error] = "There was an error adding the collaborator. Please try again."
    end
    redirect_to edit_wiki_path wiki
  end

  def destroy
    user = User.find(params[:user_id])
    wiki = Wiki.find(params[:wiki_id])
    collaborator = wiki.collaborators.where(user: user).first
    if collaborator.destroy
      flash[:notice] = "Removed a collaborator for '#{wiki.title}'"
    else
      flash[:error] = "There was an error removing the collaborator. Please try again."
    end
    redirect_to edit_wiki_path wiki
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:show]

  def update
    if current_user.update_attributes(user_params)
      flash[:notice] = "User information updated"
      redirect_to edit_user_registration_path
    else
      flash[:error] = "Invalid user information"
      redirect_to edit_user_registration_path
    end
  end

  def upgrade
    @user = User.find(params[:user_id])
    @user.update(role: 'premium')
    # @user.save
    redirect_to root_path
  end

  def downgrade
    @user = User.find(params[:user_id])
    @user.update(role: 'standard')
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :role)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
    @collaborations = Collaborator.where(wiki_id: @wiki)
    @collaborators = User.where(id: @collaborations.pluck(:user_id))
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  def create
    @wiki = Wiki.new(wiki_attributes)
    authorize @wiki

    if @wiki.save
      flash[:notice] = "Wiki was sucessfully saved."
    else
      flash[:error] = "THere was an error saving the wiki."
    end
      redirect_to edit_wiki_path @wiki
  end

  def edit
    @wiki = Wiki.find(params[:id])
    @users = User.all
    authorize @wiki
    
  end

  def update
    @wiki = Wiki.find(params[:id])
    authorize @wiki

    if @wiki.update_attributes(wiki_attributes)
      flash[:notice] = "Wiki was succesfully updated"
    else
      flash[:error] = "There was an error updating the wiki. Please try again."
    end
    redirect_to edit_wiki_path @wiki
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    
    if @wiki.destroy
      flash[:notice] = "\" #{@wiki.title}\" was succesfully destroyed."
    else
      flash[:error] = "There was an error deleting the wiki. Please try agian."
    end
    redirect_to wikis_path
  end

  private

  def wiki_attributes
    params.require(:wiki).permit(:title,:body,:private)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown_to_html(markdown)
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render markdown).html_safe
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<h2>Premium Membership</h2>
<h4>Upgrade to a Premium Blocipedia Membership today!</h4>
<br>
<div class="row">
  <div class="col-md-4">
    <p>Upgrading your account will enable these amazing features:</p>
    <ul>
      <li>Create private wikis</li>
      <li>Invite collaborators to your private wikis</li>
      <li>Feel like a boss with premium status</li>
    </ul>
    <br>
  </div>
  <div class="col-md-3">
    <% if current_user.role == 'standard' %>
      <%= form_tag charges_path do %>
        <article>
          <label class="amount">
            <span style="color:green">Amount: $15.00</span>
          </label>
        </article>
        <script 
          class='stripe-button' src="https://checkout.stripe.com/checkout.js" 
          data-key="<%= @stripe_btn_data[:key] %>" 
          data-amount=<%= @stripe_btn_data[:amount] %> 
          data-description="<%= @stripe_btn_data[:description] %>" >
        </script>
      <% end %>
    <% else %>
      <i>You are already a premium member. Thanks for your business!</i>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <ul class="nav nav-tabs">
      <li><%= link_to "Home", root_path %></li>
      <% if current_user %>
        <li><%= link_to "Wikis", wikis_path %></li>
        <% if current_user.role == 'standard' %>
          <li><%= link_to 'Upgrade',  new_charge_path %></li>
        <% end %>
      <% end %> 

      <div class="pull-right user-info">
       <% if current_user %>
         Hello <%= link_to (current_user.name || current_user.email)+" (#{current_user.role} user)", edit_user_registration_path %>  || <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
       <% else %>
         <%= link_to "Sign In", new_user_session_path %> or
         <%= link_to "Sign Up", new_user_registration_path %>
       <% end %>
     </div>
    </ul>
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:error] %>
      <div class="alert alert-danger">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:error] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>
  <%= yield %>
</div>

</body>
</html>

app/views/welcome/index.html.erb
<div class="jumbotron">
  <h1>Blocipedia</h1>
  <p>Blocipedia is a web application that allows you to create public and private Markdown-based wikis</p>
  <p>
      <%= link_to "Sign In", new_user_session_path, class: 'btn btn-primary' %> or
      <%= link_to "Sign Up", new_user_registration_path, class: 'btn btn-primary' %> today!
  </p>
</div>

<div class="row">
  <div class="col-md-4">
    <h2>Collaboration</h2>
    <p>Collaborate on community-sourced content!</p>
  </div>
  <div class="col-md-4">
    <h2>Hobbies? Work?</h2>
    <p>Wikis are not exclusive to any topic. If you have information to share, go ahead and contibute!</p>
  </div>
  <div class="col-md-4">
    <h2>Premium Accounts</h2>
    <p>Premium membership means you get to create private wikis.</p>
  </div>
</div>
<script type="text/javascript">
  $(document).ready(function(){
    blocmetrics.report("Front_Page_Visited");
  });
</script>

app/views/wikis/_form.html.erb
  <div class="row">

  <div class="col-md-8">
    <h4>Modify Contents</h4>
      <%= form_for wiki do |f| %>

        <% if wiki.errors.any? %>
          <div class="alert alert-danger">
            <h4>There are <%= pluralize(wiki.errors.count, "error") %>.</h4>
            <ul>
              <% wiki.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <% if wiki.can_modify_wiki?(current_user) %>
          <div class="form-group">
            <%= f.label :private, class: 'checkbox' do %>
            <%= f.check_box :private %> Private Wiki
            <% end %>
          </div>
        <% end %>

        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
        </div>

        <div class="form-group">
          <%= f.label :body %>
          <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
        </div>

        <div class="form-group">
          <%= f.submit "Save", class: 'btn btn-success' %>
        </div>

      <% end %>

  </div>

  <% if @wiki.can_modify_wiki?(current_user) %>
    <div class="col-md-4">
      <h4>Existing Collaborators</h4>
      <table class="table">

        <thead>
          <th>Name</th>
          <th>Action</th>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.name %></td>
              <td>
                <% if @wiki.users.include? user %>
                  <%= link_to '<i class="fa fa-minus-circle"></i>'.html_safe, wiki_collaborator_path(wiki_id: @wiki.id, user_id: user.id), method: :delete, class: 'btn btn-danger' %>
                <% else %>
                  <%= link_to '<i class="fa fa-plus-circle"></i>'.html_safe, wiki_collaborators_path(wiki_id: @wiki.id, user_id: user.id), method: :post, class: 'btn btn-success' %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>

      </table>

    </div>
  <% end %>
</div>

app/views/wikis/destroy.html.erb
<h1>Wikis#destroy</h1>
<p>Find me in app/views/wikis/destroy.html.erb</p>

app/views/wikis/edit.html.erb
<h1>Edit a Wiki</h1>
<%= link_to "<< return to the wiki", @wiki %>
<br><br>
<p>You are editing a wiki. Guidelines: Make sure the information is accurate!</p>
<%= render partial: 'form', locals: {wiki: @wiki} %>

app/views/wikis/index.html.erb
<h1>All Wikis</h1>
<%= link_to 'New Wiki', new_wiki_path(Wiki.new), class: 'btn btn-success' %>
<br><br>
<% @wikis.each do |wiki| %>
  <p><%= link_to wiki.title, wiki_path(wiki.id) %></p>
<% end %>

<script type="text/javascript">
  $(document).ready(function(){
    blocmetrics.report("Visited_wiki_index");
  });
</script>

app/views/wikis/new.html.erb
<h1>Create a Wiki</h1>

<div class="row">
  <p>You are creating a wiki. Guidelines: Make sure the information is accurate!</p>
</div>
<div class="row">
  <div class="col-md-6">
    <%= form_for @wiki do |f| %>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
      </div>
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
      </div>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
    <% end %>
  </div>
</div>

</div>

app/views/wikis/show.html.erb
<br>
<% if @wiki.private %>
  <p><i>Note: this wiki is private</i></p>
<% end %>
<%= link_to "Edit Wiki", edit_wiki_path(@wiki), class: 'btn btn-success' %>
<%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this wiki?' } %>
<div class='row'>
  <div class='col-md-8'>
    <h2><%= markdown_to_html @wiki.title %></h2>

    <p><%= markdown_to_html @wiki.body %></p>
  </div>
  <div class='col-md-4 bg-success'>
    <p><b>Collaborators:</b></p>
    <ul>
      <% @collaborators.each do |user| %>
        <li><%= user.name %></li>
      <% end %>
    </ul>
  </div>
</div>

<script type="text/javascript">
  $(document).ready(function(){
    blocmetrics.report("Viewed_wiki_page");
  });
</script>